SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `consultation`;
TRUNCATE TABLE `course_history`;
TRUNCATE TABLE `email`;
TRUNCATE TABLE `member_consultation`;
TRUNCATE TABLE `order_`;
TRUNCATE TABLE `payment`;
TRUNCATE TABLE `refund`;
TRUNCATE TABLE `salary`;
TRUNCATE TABLE `salary_note`;
TRUNCATE TABLE `sms`;
TRUNCATE TABLE `teacher`;
TRUNCATE TABLE `teacher_file`;
TRUNCATE TABLE `user_`;
TRUNCATE TABLE `user_login`;
TRUNCATE TABLE `consultation_history`;
TRUNCATE TABLE `course`;
TRUNCATE TABLE `evaluation_status`;
TRUNCATE TABLE `ldf`;
TRUNCATE TABLE `level_test`;
TRUNCATE TABLE `order_product`;
TRUNCATE TABLE `reservation`;
TRUNCATE TABLE `schedule`;
TRUNCATE TABLE `sms_target`;
SET FOREIGN_KEY_CHECKS = 1;